Look for and use the enhanced GNU getopt command (#2)
This allows for long option names to our sub-commands.

This does not assume the user has replaced their standard
getopt command with the GNU version. It just looks for it
in the conventional locations for brew and macports
installations.

diff --git a/git-hooks b/git-hooks
--- a/git-hooks
+++ b/git-hooks
@@ -24,6 +24,33 @@ GITHOOKS=(
     post-rewrite
 )
 
+
+# GETOPT
+#############################################
+# We depend on GNU getopt for option parsing, but we don't expect
+# OSX users to install it over their built-in getopt command.
+
+set +e
+getopt -T &>/dev/null
+if [[ $? -eq 4 ]]; then
+    getopt=getopt
+elif brew --prefix gnu-getopt &>/dev/null; then
+    getopt=$(brew --prefix gnu-getopt)/bin/getopt
+elif command -v port &>/dev/null; then
+    getopt=/opt/local/bin/getopt
+else
+    echo "Could not find GNU getopt. Exiting." >&2
+    exit 1
+fi
+
+# Final check because 'brew --prefix' can return a path that points to nothing.
+if ! command -v $getopt &>/dev/null; then
+    echo "Could not find GNU getopt. Exiting." >&2
+    exit 1
+fi
+set -e
+
+
 # HELP
 #############################################
 read -r -d '' HELP <<'HELP' || :
@@ -232,7 +259,7 @@ function git_hooks__extract_help {
 function git_hooks__extract_doc {
     local doc_type
 
-    eval set -- "$(getopt -o ah -- $@)"
+    eval set -- "$($getopt -o ah -- $@)"
     while [[ $1 != -- ]]; do
         case $1 in
             -a) doc_type=ARGS; shift;;
@@ -286,7 +313,7 @@ HELP
 
     local link item answer firsttime examples=false no_preserve=false
 
-    eval set -- "$(getopt -o e --long examples,no-preserve -- $@)"
+    eval set -- "$($getopt -o e --long examples,no-preserve -- $@)"
     while [[ $1 != -- ]]; do
         case $1 in
             -e|--examples) examples=true; shift;;
@@ -732,7 +759,7 @@ HELP
 
     local name quiet=false
 
-    eval set -- "$(getopt -o q --long quiet -- "$@")"
+    eval set -- "$($getopt -o q --long quiet -- $@)"
     while [[ $1 != -- ]]; do
         case $1 in
             -q|--quiet) quiet=true; shift;;
@@ -766,7 +793,7 @@ HELP
 
     local name quiet=false
 
-    eval set -- "$(getopt -o q --long quiet -- "$@")"
+    eval set -- "$($getopt -o q --long quiet -- $@)"
     while [[ $1 != -- ]]; do
         case $1 in
             -q|--quiet) quiet=true; shift;;
@@ -799,7 +826,7 @@ HELP
 
     local hook name path
 
-    eval set -- "$(getopt -o q --long quiet -- "$@")"
+    eval set -- "$($getopt -o f --long force -- $@)"
     while [[ $1 != -- ]]; do
         case $1 in
             -f|--force) export GITHOOKS_RUN=true; shift;;
