Rename alias->command, style updates
Renames `git hooks install-alias` to `git hooks install-command`, since the
desired effect is to install the `git hooks` command. The fact that it's
accomplished via an alias is an incidental implementation detail.

It also changes the default setting to install the command as a global alias
rather than a local one.

Other minor changes:
- Removed the `--examples` option to the `install` command
- Enabled support for symlinking to the git-hooks script
- Add the pre-commit-01-readme script to automatically update README.md

diff --git a/git-hooks b/git-hooks
--- a/git-hooks
+++ b/git-hooks
@@ -7,10 +7,10 @@ bash_source="${BASH_SOURCE[0]}"
 while [[ -h "$bash_source" ]]; do
   bash_source_dir="$(cd -P "$(dirname "$bash_source")" >/dev/null && pwd)"
   bash_source="$(readlink "$bash_source")"
-  [[ "$bash_source" != /* ]] && bash_source="$bash_source_dir/$bash_source"
+  [[ "$bash_source" != /* ]] && bash_source="${bash_source_dir}/${bash_source}"
 done
 bash_source_dir="$(cd -P "$(dirname "$bash_source")" >/dev/null && pwd)"
-bash_source="${bash_source_dir}/${bash_source_dir##*/}"
+bash_source="${bash_source_dir}/${bash_source##*/}"
 
 # shellcheck disable=1090
 . "${bash_source_dir}/included/lib/colors.sh" "${bash_source_dir}/included/lib"
@@ -174,7 +174,7 @@ $(md_no_indent_or_hash "
     # way of ensuring all of your future cloned and created repositories automatically
     # get $(md_inline_quotes "git hooks") support right out of the box.
 ")
-$(md_block_monospace '    path/to/git-hooks/git-hooks install-alias --global')
+$(md_block_monospace '    path/to/git-hooks/git-hooks install-command --global')
 
 $(md '#### ')$(md_no_indent_or_hash "    # Install the multiplexers and the 'git hooks' alias in a repository")
 $(md_block_monospace '
@@ -205,8 +205,8 @@ $(md '##') Usage:
     or: git hooks $(git_hooks__extract_desc run)
     or: git hooks $(git_hooks__extract_desc install)
     or: git hooks $(git_hooks__extract_desc uninstall)
-    or: git hooks $(git_hooks__extract_desc install-alias)
-    or: git hooks $(git_hooks__extract_desc uninstall-alias)
+    or: git hooks $(git_hooks__extract_desc install-command)
+    or: git hooks $(git_hooks__extract_desc uninstall-command)
     or: git hooks $(git_hooks__extract_desc install-template)
     or: git hooks $(git_hooks__extract_desc uninstall-template)
     or: git hooks $(git_hooks__extract_desc include)
@@ -356,7 +356,7 @@ function git_hooks__extract_help {
     while read -r cmd; do
         printf "\\n    %s\\n" "$(git_hooks__extract_desc "$cmd")"
         git_hooks__extract_doc -h "git_hooks_${cmd//-/_}" | sed 's/^/    /g'
-    done < <(grep "$(git_hooks__extract_desc [-a-zA-Z0-9]\+)$" "$bash_source" | sed 's/.* \(.*\))/\1/g')
+    done < <(grep "\$(git_hooks__extract_desc [-a-z]\\+)\$" "${bash_source}" | sed 's/.* \(.*\))/\1/g')
 }
 
 
@@ -436,14 +436,13 @@ function git_hooks_install {
 
 	    If --no-alias is specified, the local 'git hooks' alias will
 	    not be created.
-
 	HELP
 
     local item preserve=true alias=true
 
-    eval set -- "$($getopt --long no-preserve,no-alias -- "$@")"
-    while [[ $1 != -- ]]; do
-        case $1 in
+    eval set -- "$($getopt -o "" --long no-preserve,no-alias -- "$@")"
+    while [[ ${1:-} != -- ]]; do
+        case ${1:-} in
             --no-preserve) preserve=false; shift;;
             --no-alias) alias=false; shift;;
             *) echo "Unrecognized option: $1"; return 1;;
@@ -453,8 +452,7 @@ function git_hooks_install {
 
     # Create hooks alias if not already present
     if $alias && ! git hooks &>/dev/null; then
-        # shellcheck disable=SC2119
-        git_hooks_install_alias
+        git_hooks_install_command --local
     fi
 
     # Create the .git/hooks and .githooks directories
@@ -462,7 +460,7 @@ function git_hooks_install {
 
     # Move existing hooks to .githooks dir
     # shellcheck disable=SC2015
-    "$preserve" && echo "Moving existing hooks to $githooks_dir..." ||:
+    "$preserve" && echo "Moving existing hooks to $githooks_dir..."
     shopt -s nullglob
     for item in "${repo_git_hooks_dir}/"*; do
         if ! [[ -h "$item" && "$(readlink "$item")" =~ git-hooks-multiplexer ]]; then
@@ -478,7 +476,7 @@ function git_hooks_install {
     echo "Installing multiplexers..."
     for hook in "${git_hook_names[@]}"; do
         item="${repo_git_hooks_dir}/${hook}"
-        if ! [[ -h "$item" && "$(readlink "$item")" =~ git-hooks-multiplexer ]]; then
+        if ! [[ -h "$item" && "$(readlink "$item")" == "${bash_source_dir}/git-hooks-multiplexer" ]]; then
             ln -isv "${bash_source_dir}/git-hooks-multiplexer" "${repo_git_hooks_dir}/${hook}"
         fi
     done
@@ -495,7 +493,7 @@ function git_hooks_uninstall {
 
     # Remove hooks alias if present in repo config
     # shellcheck disable=SC2119
-    git_hooks_uninstall_alias
+    git_hooks_uninstall_command --local
 
     echo "Removing multiplexers..."
     for hook in "${repo_git_hooks_dir}/"*; do
@@ -508,39 +506,42 @@ function git_hooks_uninstall {
 
 
 # shellcheck disable=SC2120
-function git_hooks_install_alias {
+function git_hooks_install_command {
     : <<-ARGS
-	    [--global] [--core]
+	    [--local] [--global] [--core]
 	ARGS
     : <<-HELP
 	    Installs 'git-hooks' alias into any of three locations.
-	        --global: Add it to the global git aliases
+	        --local: add it to the current repository's git aliases
+	        --global: add it to the global git aliases
 	        --core: Links this file into this machine's git core
 	                directory. Any 'hooks' aliases will no longer be
 	                effective.
 
-	    If neither --global nor --core are specified, the alias will be
-	    installed into the repo's local git config.
+	    If neither --local nor --core are specified, the alias will be
+	    installed into the global git config.
 	HELP
 
     local token repo=false global=false core=false choice
 
     for token in "$@"; do
         case $token in
+            --local) shift; repo=true;;
             --global) shift; global=true;;
             --core) shift; core=true;;
             *) echo "Unknown option: $token"; return 1;;
         esac
     done
-    $global || $core || repo=true
+    $repo || $core || global=true
 
     if $repo; then
-        git config alias.hooks "!$bash_source" && \
+        git_hooks__require_git_dir
+        git config alias.hooks "!${bash_source}" && \
             echo "Added \"hooks\" to your repository's aliases."
     fi
 
     if $global; then
-        git config --global alias.hooks "!$bash_source" && \
+        git config --global alias.hooks "!${bash_source}" && \
             echo "Added \"hooks\" to your global aliases."
     fi
 
@@ -549,7 +550,7 @@ function git_hooks_install_alias {
         echo -n "Continue? (y/N) "
         read -r choice
         case $choice in
-            y|Y) ln -isv "$bash_source" "$(git --exec-path)" || \
+            y|Y) ln -isv "${bash_source}" "$(git --exec-path)" || \
                 ( \
                     echo "Could not link to $(git --exec-path)/git-hooks" && \
                     return 1 \
@@ -562,30 +563,33 @@ function git_hooks_install_alias {
 
 
 # shellcheck disable=SC2120
-function git_hooks_uninstall_alias {
+function git_hooks_uninstall_command {
     : <<-ARGS
-	    [--global] [--core]
+	    [--local] [--global] [--core]
 	ARGS
     : <<-HELP
 	    Clears the 'git-hooks' alias from the specified location.
+	        --local: Remove it from the repository's aliases
 	        --global: Remove it from the global aliases
 	        --core: Delete the git-hooks link from this machine's git
 	                core directory.
 
-	    If neither --global nor --core are specified, the alias will be
-	    removed from the repo's local git config.
+	    If neither --local nor --core are specified, the alias will be
+	    removed from the global git config.
 	HELP
     local token repo=false global=false core=false choice
     for token in "$@"; do
         case $token in
+            --local) shift; repo=true;;
             --global) shift; global=true;;
             --core) shift; core=true;;
             *) echo "Unknown option: $token"; return 1;;
         esac
     done
-    $global || $core || repo=true
+    $repo || $core || global=true
 
     if $repo; then
+        git_hooks__require_git_dir
         git config --unset alias.hooks && \
             echo "Removed from your repository's aliases."
     fi
@@ -788,7 +792,7 @@ function git_hooks_list {
 
         if [[ -n "$hooks" ]]; then
             # shellcheck disable=SC2015
-            "$disabled" && echo -en "${c_error:?}" ||:
+            "$disabled" && echo -en "${c_error:?}"
             "$unicode" && echo -en "${hook_name}─┐${c_reset}" || echo -en "${hook_name}-|${c_reset:?}"
             "$disabled" && echo " (disabled)" || echo
             echo -en "${hooks:2}" | xargs -0 -L1 printf " %${#hook_name}s%s\\n" ""
@@ -1097,7 +1101,7 @@ fi
 last_check="$(git config --global git-hooks.last-check 2>/dev/null)" || last_check=0
 if (( "$(date -v "-7d" "+%s" 2>/dev/null || date -d "last week" "+%s")" > last_check )); then
     (
-        cd "$(dirname "$bash_source")";
+        cd "$bash_source_dir";
         git fetch &>/dev/null;
         behind="$(git rev-list HEAD..origin/master | wc -l)";
         if ((behind)); then
@@ -1134,7 +1138,7 @@ case "$git_hooks_command" in
         fi
         ;;
 
-    check-support|install-alias|uninstall-alias|install-template|uninstall-template|config|help)
+    check-support|install-command|uninstall-command|install-template|uninstall-template|config|help)
         ;;
 
     *)  echo "git: '$git_hooks_command' is not a git-hooks command. See 'git hooks help'." >&2
diff --git a/git-hooks-multiplexer b/git-hooks-multiplexer
--- a/git-hooks-multiplexer
+++ b/git-hooks-multiplexer
@@ -1,31 +1,39 @@
 #!/usr/bin/env bash
-set -e
+set -eu -o pipefail
+# Determine which git hook is being run and make sure we're not accidentally
+# being called from another multiplexer script.
+# shellcheck disable=2155
+[[ -z ${HOOK:-} ]] && export HOOK=$(basename "$0") || exit
 
-# Make sure we're not accidentally being called from another multiplexer script
-[[ -z $HOOK ]] && export HOOK=$(basename "$0") || exit
-
-# Determine if we're being run explicitly from git-hooks
+# Determine if we're being run explicitly with "git-hooks run ...""
 export GITHOOKS_RUN=${GITHOOKS_RUN:-false}
-export GITHOOKS_HOME=$(dirname $(git config alias.hooks) | sed 's/!//')
 
-# This script will run all configured hooks found in <repository>/.githooks
-# and all hooks found by running:
-#
-#    git config --get-regexp "hooks\.$HOOK\.enabled" true
+# Get our installed location
+unset CDPATH
+bash_source="${BASH_SOURCE[0]}"
+while [[ -h "$bash_source" ]]; do
+  bash_source_dir="$(cd -P "$(dirname "$bash_source")" >/dev/null && pwd)"
+  bash_source="$(readlink "$bash_source")"
+  [[ "$bash_source" != /* ]] && bash_source="$bash_source_dir/$bash_source"
+done
+bash_source_dir="$(cd -P "$(dirname "$bash_source")" >/dev/null && pwd)"
+bash_source="${bash_source_dir}/${bash_source##*/}"
+
+# This script will run all configured hooks found in <repository>/.githooks/$HOOK.
 #
 # It will fail if any of those return non-zero exit codes. You can disable
-# individual hooks through git configs:
+# individual hooks with the 'git hooks disable' command:
 #
 #    # Disable all custom hooks for this git hook
-#    git config --bool hooks.$HOOK.enabled false
+#    git hooks disable <hook>
 #
 #    # Disable an individual custom hook
-#    git config --bool hooks.<custom hook>.enabled false
+#    git hooks disable <custom-hook>
 #
-# The hooks will be run sequentially by default for safety.
+# The hook scripts will be run sequentially by default for safety.
 # If you determine that your hooks can be run in parallel, enable it with:
 #
-#    git config --int hooks.$HOOK.parallel <num>
+#    git config --int hooks.<hook>.parallel <num>
 #
 # where <num> is the number of jobs you wish to start. If 0, <num> will
 # be interpretted as the number of CPUs on the machine. When running in
@@ -33,14 +41,14 @@ export GITHOOKS_HOME=$(dirname $(git config alias.hooks) | sed 's/!//')
 # choose to not run your hooks in parallel, the output will not be buffered.
 #
 # For safety, you can check for parallel execution in your hook by calling
-# the prevent-parallel function. It checks the value of
-# "git config hooks.$HOOK.parallel" and exits will non-zero exit code if it is
-# set to anything but 1.
+# the "prevent-parallel" function. It checks the value of
+# "git config hooks.<hook>.parallel" and exits with a non-zero exit code
+# if it is set to anything but 1.
 #
 #    Example:
 #        #!/usr/bin/env bash
-#        prevent-parallel   # Will fail the hook unless
-#                           # it is being run sequentially.
+#        prevent-parallel   # Will fail the hook unless it is being run
+#                           # sequentially.
 #
 
 CAPTURE=/tmp/capture.$$
@@ -106,18 +114,19 @@ tmpfile=$(mktemp -t git_hooks.XXXX)
 count=0
 
 # Set a trap to clean up our temp file
+# shellcheck disable=2064
 trap "rm -f ${tmpfile}*" EXIT SIGHUP SIGINT SIGTERM
 
 # Look in the default location of .githooks
-if ls .githooks/${HOOK}-* &>/dev/null; then
-    for hook in .githooks/${HOOK}-*; do
+if ls ".githooks/${HOOK}-"* &>/dev/null; then
+    for hook in ".githooks/${HOOK}-"*; do
         if [[ -f ${hook} && -n ${hook%%*~} ]]; then
-            if { ! $GITHOOKS_RUN; } && { git config --get-regexp "hooks\.$HOOK\.enabled" false &>/dev/null \
-                || git config --get-regexp "hooks\.${hook##*/}\.enabled" false &>/dev/null; }; then
+            if { ! $GITHOOKS_RUN; } && { git config --get-regexp "hooks\\.$HOOK\\.enabled" false &>/dev/null \
+                    || git config --get-regexp "hooks\\.${hook##*/}\\.enabled" false &>/dev/null; }; then
                 disabled="${disabled:+$disabled\0}$hook"
             elif [[ ! -x $hook ]]; then
                 if included_hook=$(git config -f "$hook" git-hooks.included 2>/dev/null); then
-                    hook="$GITHOOKS_HOME/included/$included_hook"
+                    hook="$bash_source_dir/included/$included_hook"
                     hooks="${hooks:+$hooks\0}$tmpfile.$((count++)) $tmpfile.stdin $hook"
                 else
                     nonexecutable="${nonexecutable:+$nonexecutable\0}$hook"
@@ -129,30 +138,14 @@ if ls .githooks/${HOOK}-* &>/dev/null; then
     done
 fi
 
-# Make sure that each configured hook can be found,
-# Otherwise, fail after running the ones we cound find.
-while read line; do
-    section=${line%.enabled*}
-    path=$(git config $section.path) || continue
-    hook=${section#hooks\.}
-    if [[ ! -e $path ]]; then
-        missing="${missing:+$missing\0}$hook - $path"
-    elif [[ ! -x $path ]]; then
-        nonexecutable="${nonexecutable:+$nonexecutable\0}$hook - $path"
-    elif { ! $GITHOOKS_RUN; } && git config --get-regexp "hooks\.$HOOK\.enabled" false &>/dev/null; then
-        disabled="${disabled:+$disabled\0}$path"
-    else
-        hooks="${hooks:+$hooks\0}$tmpfile.$((count++)) $tmpfile.stdin $path"
-    fi
-done < <(git config --get-regexp "hooks\.${HOOK}-.*\.enabled" true)
-
 # Display disabled hooks
-if [[ -n $disabled ]]; then
+if [[ -n "$disabled" ]]; then
     echo -e "[skipping disabled hooks]"
-    echo -en $disabled | xargs -0 -L1 | sed "s/^\(.*\)/    [\1]/"
+    echo -en "$disabled" | xargs -0 -L1 | sed "s/^\\(.*\\)/    [\\1]/"
 fi
+
 # Might be done already
-if [[ -z $hooks ]] && [[ -z $missing ]] && [[ -z $nonexecutable ]]; then
+if [[ -z "$hooks" ]] && [[ -z "$missing" ]] && [[ -z "$nonexecutable" ]]; then
     exit
 fi
 
@@ -163,48 +156,44 @@ function is-parallel {
 }
 export -f is-parallel
 
-hooks_parallel="-P $(git config hooks.$HOOK.parallel)" || hooks_parallel=
-if [[ max == $(git config hooks.$HOOK.parallel) ]]; then
+# Decide whether to run in parallel or sequentially
+hooks_parallel="-P $(git config "hooks.${HOOK}.parallel")" || hooks_parallel=
+if [[ max == $(git config "hooks.{$HOOK}.parallel") ]]; then
     hooks_parallel="-P $(grep -c processor /proc/cpuinfo)"
 fi
 
 # Set a trap to display any bufferred output and clean up our temp files
+# shellcheck disable=2064
 trap "rm -f ${tmpfile}.stdin; cat ${tmpfile}* 2>/dev/null; rm -f ${tmpfile}*" EXIT SIGHUP SIGINT SIGTERM
 
 # Save our stdin so we can feed it to multiple scripts
-[[ -t 0 ]] && touch ${tmpfile}.stdin || cat >${tmpfile}.stdin
+# shellcheck disable=2015
+[[ -t 0 ]] && touch "${tmpfile}.stdin" || cat >"${tmpfile}.stdin"
 
-# Decide whether to run in parallel or sequentially
-if [[ -n $hooks_parallel ]]; then
-    # Run the hooks through xargs. If any of them fail, xargs will fail and the script
-    # will exit with an error code due to the -e at the top of this script.
-    echo -en $hooks | xargs -0 -I {} $hooks_parallel bash -e $CAPTURE {} $*
-else
-    IFS=$'\n'
-    for hook in $(echo -e $(echo $hooks | sed 's/\\0/\\n/g')); do
-        bash -e $CAPTURE $hook $*
-    done
-    unset IFS
-fi
+# Run the hooks through xargs. If any of them fail, xargs will fail and the script
+# will exit with an error code due to the -e at the top of this script.
+# shellcheck disable=2086
+echo -en "$hooks" | xargs -0 -I {} $hooks_parallel bash -e "$CAPTURE" {} "$@"
 
 # All hooks succeeded, reset our trap for cleanup and manually display the results
+# shellcheck disable=2064
 trap "rm -f ${tmpfile}* /tmp/capture.$$" EXIT SIGHUP SIGINT SIGTERM
-rm ${tmpfile}.stdin
-cat ${tmpfile}* 2>/dev/null || :
+rm "${tmpfile}.stdin"
+cat "${tmpfile}"* 2>/dev/null || :
 
-if [[ -n $missing || -n $nonexecutable ]]; then
+if [[ -n "$missing" || -n "$nonexecutable" ]]; then
     # Fail the hook if we couldn't find one of the hook scripts (even though we ran
     # the ones we found and encountered no errors)
-    if [[ -n $missing ]]; then
+    if [[ -n "$missing" ]]; then
         echo -e "[failed $HOOK checks due to missing hooks]"
-        echo -en $missing | xargs -0 -L1 | sed "s/^\(.*\)/    [\1]/"
+        echo -en "$missing" | xargs -0 -L1 | sed "s/^\\(.*\\)/    [\\1]/"
     fi
 
     # Fail the hook if we couldn't execute one of the hook scripts (even though we
     # ran the ones we found and encountered no errors)
-    if [[ -n $nonexecutable ]]; then
+    if [[ -n "$nonexecutable" ]]; then
         echo -e "[failed $HOOK checks due to non-executable hooks]"
-        echo -en $nonexecutable | xargs -0 -L1 | sed "s/^\(.*\)/    [\1]/"
+        echo -en "$nonexecutable" | xargs -0 -L1 | sed "s/^\\(.*\\)/    [\\1]/"
     fi
 
     exit 1
